services:
  mysql:
    image: mysql:8.3
    container_name: project-ecommerce-mysql
    restart: always
    environment:
      MYSQL_DATABASE: order_management
      MYSQL_ROOT_PASSWORD: '@root0302'
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: project-ecommerce-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/order_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '@root0302'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # or none, validate, create-drop, etc.
    restart: on-failure
